# Generated by Django 5.0.4 on 2024-05-22 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_student_gender_alter_teacher_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.school'),
            preserve_default=False,
        ),
    ]
