# Generated by Django 5.0.4 on 2024-05-22 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_classroom_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='School',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='apis.classroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='year',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'year', 'room')},
        ),
    ]
