# Generated by Django 5.0.4 on 2024-05-22 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_student_school_student_classroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='School',
            new_name='school',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.classroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.school'),
            preserve_default=False,
        ),
    ]
