# Generated by Django 5.0.4 on 2024-05-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_rename_school_student_school_teacher_classroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classroom',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classroom',
            field=models.ManyToManyField(blank=True, to='apis.classroom'),
        ),
    ]
