# Generated by Django 5.0.4 on 2024-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_remove_teacher_classroom_teacher_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'surname')},
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('name', 'surname')},
        ),
    ]
